In [1]:
import numpy as np
a = np.array([1,2,3,3])
print('a的shape是：')
print(a.shape)
b = np.array([[1,1],[1,1],[1,1]])
print('b的shape是：')
print(b.shape)


a的shape是：
(4,)
b的shape是：
(3, 2)


In [5]:
def pysum():
    a = [0, 1, 2, 3, 4,]
    b = [9, 8, 7, 6, 5,]
    c = []
    for i in range(len(a)):
        c.append(a[i]**2 + b[i]**2)
    return c
print(pysum())
########################################
import numpy as np
def npsum():
    a = np.array([0, 1, 2, 3, 4,])
    b = np.array([9, 8, 7, 6, 5,])
    c = a**2 + b**2
    return c
print(npsum())

[81, 65, 53, 45, 41]
[81 65 53 45 41]


In [8]:
import numpy as np
a=[1,2,3,4]
b=np.array([1,2,3,4])
print(a)
print(b)
c=a*2
d=b*2
print(c)
print(d)
e=[[1,2],[3,4],[5,6]]
f=np.array([[1,2],[3,4],[5,6]])
print(e)
print(f)

[1, 2, 3, 4]
[1 2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
import numpy as np
a1=np.array([1,2,3,4])
lst1=[3.14,2.17,0,1,2]
a2=np.array([[1,2],[3,4],[5,6]])
a3=np.array(lst1)
print(a2)
print(a3)

[[1 2]
 [3 4]
 [5 6]]
[3.14 2.17 0.   1.   2.  ]


In [12]:
x1=np.arange(12)
x2=np.arange(5,10)
x3=np.random.randn(3,3)
x4=np.random.random([3,3])
x5=np.ones((2,4))
x6=np.zeros((3,4))
x7=np.linspace(2,8,3,dtype=np.int32)
print(x1)
print(x2)
print(x3)
print(x4)
print(x5)
print(x6)
print(x7)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[5 6 7 8 9]
[[-1.56233759  0.8746619  -0.15799036]
 [-0.56180239 -0.61494341 -0.69827126]
 [-0.66539546  1.16099223 -1.41587553]]
[[0.24024003 0.79538857 0.27694957]
 [0.64205338 0.12071625 0.10342665]
 [0.87571911 0.61208231 0.64015831]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[2 5 8]


In [6]:
import numpy as np
a = np.arange(1,7).reshape((2,3))
b = np.array([[6,7,8],[9,10,11]])
print("a:\n",a)
print("b:\n",b)
#数组加法
print("a+b:\n",a+b)
#数组减法
print("a-b:\n",a-b)
#数组乘法
print("a*b:\n",a*b)
#数组除法
print("b/a:\n",b/a)

a:
 [[1 2 3]
 [4 5 6]]
b:
 [[ 6  7  8]
 [ 9 10 11]]
a+b:
 [[ 7  9 11]
 [13 15 17]]
a-b:
 [[-5 -5 -5]
 [-5 -5 -5]]
a*b:
 [[ 6 14 24]
 [36 50 66]]
b/a:
 [[6.         3.5        2.66666667]
 [2.25       2.         1.83333333]]


In [2]:
import numpy as np
arr = np.arange(10)
print("arr:",arr)
#数组与常数之间的运算
#求加法
print("arr+1:",arr+1)
#求减法
print("arr-2:",arr-2)
#求乘法
print("arr*3",arr*3)
#求除法
print("arr/2",arr/2)

arr: [0 1 2 3 4 5 6 7 8 9]
arr+1: [ 1  2  3  4  5  6  7  8  9 10]
arr-2: [-2 -1  0  1  2  3  4  5  6  7]
arr*3 [ 0  3  6  9 12 15 18 21 24 27]
arr/2 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [10]:
import numpy as np
a = np.arange(1,7).reshape((2,3))
print("a:\n",a)
b = np.arange(3)
print("b:",b)
print("a.shape:",a.shape)
print("b.shape:",b.shape)
print("a+b:\n",a+b)
print("a-b:\n",a-b)
print("a*b:\n",a*b)

a:
 [[1 2 3]
 [4 5 6]]
b: [0 1 2]
a.shape: (2, 3)
b.shape: (3,)
a+b:
 [[1 3 5]
 [4 6 8]]
a-b:
 [[1 1 1]
 [4 4 4]]
a*b:
 [[ 0  2  6]
 [ 0  5 12]]


In [8]:
import numpy as np
a = np.arange(1,13).reshape((4,3))
b = np.arange(1,5).reshape((4,1))
print("a:\n",a)
print("b:\n",b)
print("a.shape:",a.shape)
print("b.shape:",b.shape)
print("a+b:\n",a+b)

a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b:
 [[1]
 [2]
 [3]
 [4]]
a.shape: (4, 3)
b.shape: (4, 1)
a+b:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [9]:
import numpy as np
a = np.arange(1,13).reshape((4,3))
b = np.arange(1,7).reshape((2,3))
print("a:\n",a)
print("b:\n",b)
print("a.shape:",a.shape)
print("b.shape:",b.shape)
print("a+b:\n",a+b)

a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b:
 [[1 2 3]
 [4 5 6]]
a.shape: (4, 3)
b.shape: (2, 3)


ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

In [11]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
import numpy as np
x = np.array([1,2,3])
y=x [ np.newaxis , : ]   #变成二维的行向量
z=x[ : , np.newaxis ]   #变成二维的列向量
print(x)
print(y)
print(z)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]
